export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';

export const ALL_PLAYING = 'ALL_PLAYING';

export const SET_SOUNDS = 'SET_SOUNDS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const UPDATE_CURRENT_CATEGORY = 'UPDATE_CURRENT_CATEGORY';

export const GET_FAVOURITE_CATEGORIES = 'GET_FAVOURITE_CATEGORIES';
export const SET_FAVOURITE_CATEGORIES = 'SET_FAVOURITE_CATEGORIES';
export const PLAYING_START = 'PLAYING_START';
export const PLAYING_END = 'PLAYING_END';

export const GET_PLAYING_CATEGORY = 'GET_PLAYING_CATEGORY';
export const SET_PLAYING_CATEGORY = 'SET_PLAYING_CATEGORY';
